AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AvatarApi:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: <your-ecr-image-uri>
      MemorySize: 4096
      Timeout: 900
      Environment:
        Variables:
          LOG_LEVEL: INFO 